name: Run unit tests for Matlab function as demo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Matlab
      uses: matlab-actions/setup-matlab@v2
      with:
        release: 'R2023b'
        cache: true
    - name: Run unit tests
      uses: matlab-actions/run-tests@v2
      with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
